FROM mcr.microsoft.com/devcontainers/base:ubuntu
LABEL org.opencontainers.image.source="https://github.com/ourPLCC/plcc-ng-devcontainer"
LABEL org.opencontainers.image.description="Prebuilt devcontainer with plcc-ng, Python, Java, and JavaScript"
LABEL org.opencontainers.image.licenses="GPL-3.0-or-later"
